package com.racunko.app.domain

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import com.racunko.app.data.BillDao
import com.racunko.app.data.BillEntity
import com.racunko.app.data.FileKind
import com.racunko.app.data.FileStore
import com.racunko.app.data.Gallery
import com.racunko.app.data.PayeeDao
import com.racunko.app.data.PayeeProfileEntity
import com.racunko.app.data.SafStore
import com.racunko.app.data.StoredFile
import com.racunko.app.parser.AccountChecksum
import com.racunko.app.parser.AddressEntry
import com.racunko.app.parser.AddressMatcher
import com.racunko.app.parser.AmountParser
import com.racunko.app.parser.BillName
import com.racunko.app.parser.ConfirmationParser
import com.racunko.app.parser.IpsQr
import com.racunko.app.parser.IpsQrPayload
import com.racunko.app.parser.MonthDetector
import com.racunko.app.parser.MonthYear
import com.racunko.app.parser.PairResult
import com.racunko.app.parser.PairingEngine
import com.racunko.app.parser.PayeeMemory
import com.racunko.app.parser.ProviderDetector
import com.racunko.app.parser.StoredBill
import com.racunko.app.parser.registry.NormalizedDoc
import com.racunko.app.parser.registry.SourceKind
import com.racunko.app.parser.registry.TemplateRegistry
import com.racunko.platform.Engines
import java.io.ByteArrayOutputStream

enum class CardMode { RACUN, POTVRDA }
enum class CardStatus { OK, ERROR }

data class CardItem(
    val id: String,
    val mode: CardMode,
    val origName: String,
    val uri: String,
    val provider: String = "",
    val address: String = "",
    val month: MonthYear? = null,
    val amount: Long? = null,
    val roDigits: String = "",
    /** IPS QR R field (18 digits) or account extracted from a QR-less bill. */
    val recipientAccount: String = "",
    /** Recipient name (IPS N), used when generating a QR (Change 5b). */
    val recipientName: String = "",
    /** Recipient account passed the MOD 97-10 checksum (Change 5). */
    val accountVerified: Boolean = false,
    val hasQr: Boolean = false,
    val qrPng: ByteArray? = null,
    val qrImageUri: String? = null,
    val qrNote: Boolean = false,
    /** The QR was generated by the app (Change 5b), not extracted from a source QR. */
    val qrGenerated: Boolean = false,
    /** Fields filled from payee memory (Change 6) — shown as "predloženo". */
    val providerSuggested: Boolean = false,
    val addressSuggested: Boolean = false,
    /** v1.5.2 Change B: canonical per-space id (InfoStan IDENT), "" when none. */
    val spaceId: String = "",
    /** v1.5.2 Change B2: the final name collides — ask for a space tag, no silent _2. */
    val needsSpaceTag: Boolean = false,
    val status: CardStatus = CardStatus.OK,
    val error: String? = null,
    /** Confirmation card: successfully paired with a bill. */
    val matched: Boolean = false,
    /** Bill card: its confirmation arrived. */
    val paired: Boolean = false,
    /** v1.3 Change 3: attached confirmation shown as a sub-row under the bill. */
    val pairedConfName: String? = null,
    val pairedConfUri: String? = null,
    /** Bill names offered as tap-to-pair chips on an unpaired confirmation card. */
    val pairCandidates: List<String> = emptyList(),
    val addrAmbiguous: List<String> = emptyList(),
    /** Current file name on disk. */
    val currentName: String
) {
    val nameBase: String get() = currentName.substringBeforeLast('.')
    val isComplete: Boolean get() = BillName.isComplete(provider, address, month, amount)
}

class Pipeline(
    private val context: Context,
    private val dao: BillDao,
    private val payeeDao: PayeeDao,
    /** v1.5.0-rc1: supplies the bound SAF store so QR PNGs land in the tree. */
    private val safStore: () -> SafStore? = { null }
) {

    private var seq = 0
    private fun nextId(): String = "card${seq++}_${System.currentTimeMillis()}"

    private val registry = TemplateRegistry.default()

    // ---------------------------------------------------------------- bills

    /** PDF bill: PDFBox text (+ OCR fallback) and PdfRenderer→QrDecoder for the IPS QR. */
    suspend fun processBill(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val origName = file.name
        val id = nextId()

        val text = extractTextWithOcrFallback(file.uri)
        var qr: QrResult? = null
        var qrFailed = false
        try {
            qr = QrExtractor.extract(context, file.uri)
        } catch (e: Exception) {
            qrFailed = true
        }
        if (text == null && qr == null) return errorCard(id, origName, file.uri)

        return buildBillCard(
            id, origName, file.uri, store, text, qr?.payload, qr?.qrPng, qrFailed,
            sourceKind = if (text.isNullOrBlank()) SourceKind.PDF_OCR else SourceKind.PDF_TEXT,
            addresses = addresses, overrides = overrides, bindings = bindings
        )
    }

    /**
     * Change 4: paper bill imported as a photo (or the still frame from 8d).
     * OCR the image and decode any photographed IPS QR directly from the bitmap
     * via the flavor engines, then share the same naming/storage logic.
     */
    suspend fun processImageBill(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val origName = file.name
        val id = nextId()
        val engines = Engines.instance
        val bmp = loadBitmap(file.uri)
        if (bmp == null || engines == null) return errorCard(id, origName, file.uri)

        val text = runCatching { engines.textRecognizer.recognize(bmp) }.getOrNull()
        val payload = runCatching {
            engines.qrDecoder.decode(bmp).firstOrNull { it.startsWith(IpsQr.PREFIX) }
        }.getOrNull()
        // regenerate a crisp QR PNG if an IPS code was photographed
        val qrPng = payload?.let { runCatching { engines.qrEncoder.encode(it, 660) }.getOrNull() }
        bmp.recycle()
        if (text.isNullOrBlank() && payload == null) return errorCard(id, origName, file.uri)

        return buildBillCard(
            id, origName, file.uri, store, text, payload, qrPng, qrFailed = false,
            sourceKind = SourceKind.IMAGE_OCR, addresses = addresses, overrides = overrides,
            bindings = bindings
        )
    }

    /**
     * 8d: turn a live-scanned IPS QR payload into a bill. No OCR and no
     * full-page photo (product decision) — a clean PDF artifact is generated
     * from the decoded fields + a fresh IPS QR, then run through the normal PDF
     * pipeline. Month/address come from payee memory (inside processBill) or
     * manual chips; the QR is flagged generated so the disclaimer applies.
     */
    suspend fun processScannedQr(
        payload: String,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val engines = Engines.instance ?: return errorCard(nextId(), "skenirano.pdf", Uri.EMPTY)
        val ips = IpsQr.parse(payload)
        val qr = engines.qrEncoder.encode(payload, 660)
        val lines = listOfNotNull(
            ips["N"]?.takeIf { it.isNotBlank() },
            ips["I"]?.takeIf { it.isNotBlank() }
        )
        val bytes = ScanArtifact.buildPdf(qr, lines)
        val temp = java.io.File(context.cacheDir, "scan_${System.currentTimeMillis()}.pdf")
        temp.writeBytes(bytes)
        val imported = store.importFile(
            FileKind.RACUN, Uri.fromFile(temp), "skenirano_${System.currentTimeMillis()}.pdf", "application/pdf"
        )
        runCatching { temp.delete() }
        if (imported == null) return errorCard(nextId(), "skenirano.pdf", Uri.EMPTY)

        // Build directly as QR_ONLY (no QR-derived address, Change 6) using the
        // freshly generated QR bitmap; flag it generated so the disclaimer applies.
        return buildBillCard(
            nextId(), imported.name, imported.uri, store,
            text = null, qrPayload = payload, qrPng = qr, qrFailed = false,
            sourceKind = SourceKind.QR_ONLY, addresses = addresses, overrides = overrides,
            bindings = bindings
        ).copy(qrGenerated = true)
    }

    /**
     * v1.5.2 Change A: classify a picked/shared file BEFORE import, so manual
     * add and share-into share one code path. The core's classifier decides
     * (bank-confirmation fingerprint → CONFIRMATION; bill/uplatnica fingerprint
     * or IPS QR → BILL; else UNKNOWN). Errors degrade to UNKNOWN — the app then
     * simply asks, it never blocks.
     */
    suspend fun classifyDocument(uri: Uri, isImage: Boolean): com.racunko.app.parser.registry.DocTypeGuess = try {
        val text: String?
        val qrPayload: String?
        if (isImage) {
            val bmp = loadBitmap(uri)
            val engines = Engines.instance
            if (bmp == null || engines == null) {
                text = null; qrPayload = null
            } else {
                text = runCatching { engines.textRecognizer.recognize(bmp) }.getOrNull()
                qrPayload = runCatching {
                    engines.qrDecoder.decode(bmp).firstOrNull { it.startsWith(IpsQr.PREFIX) }
                }.getOrNull()
                bmp.recycle()
            }
        } else {
            text = extractTextWithOcrFallback(uri)
            qrPayload = runCatching { QrExtractor.extract(context, uri)?.payload }.getOrNull()
        }
        val ips = qrPayload?.let { IpsQr.parse(it) }
        val kind = if (isImage) SourceKind.IMAGE_OCR else SourceKind.PDF_TEXT
        registry.classifyDocType(NormalizedDoc.of(text, ips, kind))
    } catch (_: Exception) {
        com.racunko.app.parser.registry.DocTypeGuess(
            com.racunko.app.parser.registry.DocType.UNKNOWN,
            com.racunko.app.parser.registry.GuessConfidence.LOW
        )
    }

    private fun errorCard(id: String, origName: String, uri: Uri) = CardItem(
        id = id, mode = CardMode.RACUN, origName = origName,
        uri = uri.toString(), status = CardStatus.ERROR, error = "PDF", currentName = origName
    )

    private fun loadBitmap(uri: Uri): android.graphics.Bitmap? =
        runCatching {
            context.contentResolver.openInputStream(uri)?.use {
                android.graphics.BitmapFactory.decodeStream(it)
            }
        }.getOrNull()

    /** Shared bill logic for both the PDF and image inputs. */
    private suspend fun buildBillCard(
        id: String,
        origName: String,
        sourceUri: Uri,
        store: FileStore,
        text: String?,
        qrPayload: String?,
        qrPng: android.graphics.Bitmap?,
        qrFailed: Boolean,
        sourceKind: SourceKind,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val ext = "." + origName.substringAfterLast('.', "pdf")
        val ips = qrPayload?.let { IpsQr.parse(it) }
        val rawProvider = ProviderDetector.detect(ips, text)
        val amount = AmountParser.parse(ips, text)
        val month = MonthDetector.detect(rawProvider, ips, text)
        // Change 6: on a scanned/QR-only bill the address is NEVER taken from the
        // QR (P is the payer's address, not the user's label) — pass no QR, so
        // the label comes from payee memory below or stays a manual "adresa?".
        val addrIps = if (sourceKind == SourceKind.QR_ONLY) null else ips
        val addr = AddressMatcher.detect(addresses, addrIps, text, rawProvider)

        // Change 5: recipient account (QR R, else extracted from a QR-less bill),
        // gated by the MOD 97-10 checksum — an unverified account never enables
        // QR generation and is not a pairing key.
        val recipientAccount = if (ips != null) {
            IpsQr.recipientAccountDigits(ips)
        } else {
            runCatching {
                registry.extract(NormalizedDoc.of(text, ips, sourceKind)).recipientAccount
            }.getOrNull().orEmpty()
        }
        val accountVerified = AccountChecksum.isValid(recipientAccount)
        val recipientName = ips?.get("N")?.trim().orEmpty()

        // Change 6 / v1.4.4 Change 4: prefill missing provider/address from a
        // remembered payee — but NEVER on the scan path (QR_ONLY): a scanned
        // bill's address is always blank for manual entry, no guess at all.
        val prefill = if (sourceKind == SourceKind.QR_ONLY) {
            com.racunko.app.parser.PrefillResult(rawProvider, addr.label, false, false)
        } else {
            val profile = if (accountVerified) payeeDao.byAccount(recipientAccount)?.toProfile() else null
            PayeeMemory.prefill(recipientAccount, rawProvider, addr.label) { profile }
        }
        // v1.5.2 Change B: the per-space id (InfoStan IDENT) picks up a bound
        // sub-label once set — SG26 becomes SG26-G1 automatically, every month.
        val spaceId = com.racunko.app.parser.SpaceId.detect(rawProvider, ips, text) ?: ""
        val subLabel = com.racunko.app.parser.SpaceNaming.subFor(spaceId, prefill.addressLabel, bindings)
        val addressLabel = com.racunko.app.parser.SpaceNaming.addressToken(prefill.addressLabel, subLabel)
        val providerToken = overrides[prefill.provider]?.takeIf { it.isNotBlank() } ?: prefill.provider

        var currentName = origName
        var currentUri = sourceUri
        var needsSpaceTag = false
        if (BillName.isComplete(providerToken, addressLabel, month, amount)) {
            val base = BillName.build(providerToken, addressLabel, month, amount)
            // reprocessing an already-renamed file keeps its name
            if (origName != "$base$ext" && !BillName.PROCESSED.matches(origName)) {
                val existing = store.existingNames(FileKind.RACUN) - origName
                if (com.racunko.app.parser.SpaceNaming.collides(base, ext, existing, origName)) {
                    // Change B2: identical final name (another space?) — no silent
                    // _2 suffix; the card asks for a space tag instead.
                    needsSpaceTag = true
                } else {
                    store.rename(currentUri, origName, "$base$ext", FileKind.RACUN)?.let {
                        currentUri = it
                        currentName = "$base$ext"
                    }
                }
            }
        }

        val nameBase = currentName.substringBeforeLast('.')
        var qrImageUri: String? = null
        if (qrPng != null) {
            qrImageUri = Gallery.save(context, qrPng, "${nameBase}_QR", safStore(), caption = nameBase)
        }

        val ro = IpsQr.roDigits(ips)
        var alreadyPaired = false
        if (ro.length >= 6) {
            val existing = dao.byKey(ro)
            alreadyPaired = existing?.paired ?: false
            dao.upsert(
                BillEntity(
                    roKey = ro,
                    altKey = StoredBill.altKeyOf(ro),
                    provider = providerToken,
                    address = addressLabel,
                    month = month?.month,
                    year2 = month?.year2,
                    amount = amount,
                    recipientAccount = recipientAccount,
                    finalName = nameBase,
                    qrImageUri = qrImageUri ?: existing?.qrImageUri,
                    paired = alreadyPaired,
                    timestamp = System.currentTimeMillis()
                )
            )
        }

        // Remember this payee for next month (checksum-valid accounts only).
        rememberPayee(recipientAccount, accountVerified, prefill.provider, addressLabel, recipientName, ro)

        return CardItem(
            id = id,
            mode = CardMode.RACUN,
            origName = origName,
            uri = currentUri.toString(),
            provider = providerToken,
            address = addressLabel,
            month = month,
            amount = amount,
            roDigits = ro,
            recipientAccount = recipientAccount,
            recipientName = recipientName,
            accountVerified = accountVerified,
            hasQr = qrPayload != null,
            qrPng = qrPng?.toPngBytes(),
            qrImageUri = qrImageUri,
            qrNote = qrFailed,
            paired = alreadyPaired,
            providerSuggested = prefill.providerSuggested,
            addressSuggested = prefill.addressSuggested,
            spaceId = spaceId,
            needsSpaceTag = needsSpaceTag,
            addrAmbiguous = if (addr.ambiguous) addr.all else emptyList(),
            currentName = currentName
        )
    }

    /**
     * Change 5b: generate an NBS IPS QR for a bill that has none. Gated on a
     * checksum-valid recipient account + present amount (the same gate the UI
     * enforces). Saves the PNG to the v1.3 gallery location and keeps the bill
     * record's qrImageUri in sync so pairing deletes it later.
     */
    suspend fun generateQr(item: CardItem): CardItem {
        if (!IpsQrPayload.canGenerate(item.recipientAccount, item.amount)) return item
        val engines = Engines.instance ?: return item
        val payload = IpsQrPayload.build(
            recipientAccount = item.recipientAccount,
            recipientName = item.recipientName.ifBlank { item.provider.uppercase() },
            amount = item.amount!!,
            paymentReference = item.roDigits.ifBlank { null }
        )
        val bmp = engines.qrEncoder.encode(payload, 660)
        val uri = Gallery.save(context, bmp, "${item.nameBase}_QR", safStore(), caption = item.nameBase)
        if (item.roDigits.length >= 6) {
            dao.byKey(item.roDigits)?.let { dao.upsert(it.copy(qrImageUri = uri)) }
        }
        return item.copy(
            qrPng = bmp.toPngBytes(),
            qrImageUri = uri,
            hasQr = true,
            qrGenerated = true
        )
    }

    /**
     * v1.4.7/8: produce a QR PNG for a card whose in-memory bytes were lost (a
     * restored card, v1.4.3) — extract it from the file, else regenerate from the
     * fields (checksum-valid account + amount). Lets „QR slika" work after a
     * restart / on a paid bill, independent of paired state.
     */
    suspend fun qrBytesFor(item: CardItem): ByteArray? {
        runCatching { QrExtractor.extract(context, Uri.parse(item.uri))?.qrPng }
            .getOrNull()?.let { return it.toPngBytes() }
        if (IpsQrPayload.canGenerate(item.recipientAccount, item.amount)) {
            val engines = Engines.instance ?: return null
            val payload = IpsQrPayload.build(
                recipientAccount = item.recipientAccount,
                recipientName = item.recipientName.ifBlank { item.provider.uppercase() },
                amount = item.amount!!,
                paymentReference = item.roDigits.ifBlank { null }
            )
            return engines.qrEncoder.encode(payload, 660).toPngBytes()
        }
        return null
    }

    private suspend fun rememberPayee(
        account: String,
        accountVerified: Boolean,
        provider: String,
        address: String,
        displayName: String,
        referenceShape: String
    ) {
        if (!accountVerified || provider.isBlank() || address.isBlank()) return
        payeeDao.upsert(
            PayeeProfileEntity(
                account = account,
                provider = provider,
                addressLabel = address,
                displayName = displayName.ifBlank { provider },
                lastReferenceShape = referenceShape,
                updatedAt = System.currentTimeMillis()
            )
        )
    }

    // -------------------------------------------------------- confirmations

    suspend fun processConfirmation(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        ocrText: String? = null
    ): CardItem {
        val origName = file.name
        val id = nextId()
        val isImage = ocrText != null

        val text: String? = if (isImage) ocrText else extractTextWithOcrFallback(file.uri)
        val qr: QrResult? = if (isImage) null else {
            runCatching { QrExtractor.extract(context, file.uri) }.getOrNull()
        }
        if (text == null && qr == null) {
            return CardItem(
                id = id, mode = CardMode.POTVRDA, origName = origName,
                uri = file.uri.toString(), status = CardStatus.ERROR,
                error = "PDF", currentName = origName
            )
        }

        val ips = qr?.let { IpsQr.parse(it.payload) }
        val fields = ConfirmationParser.parse(text ?: "", ips)
        val stored = dao.all().map { it.toStored() }
        val ext = "." + (origName.substringAfterLast('.', "pdf"))

        when (val result = PairingEngine.pair(fields, stored)) {
            is PairResult.Matched -> {
                val bill = result.bill
                val (newUri, newName) =
                    renameTo(file.uri, origName, store, FileKind.POTVRDA, "uplata_${bill.name}", ext)
                markPaired(bill.roKey)
                return CardItem(
                    id = id, mode = CardMode.POTVRDA, origName = origName,
                    uri = newUri.toString(),
                    provider = bill.provider, address = bill.address,
                    month = bill.month, amount = bill.amount,
                    matched = true, currentName = newName
                )
            }
            is PairResult.Candidates -> {
                return genericConfirmationCard(id, file, origName, ips, text, fields, addresses, overrides)
                    .copy(pairCandidates = result.bills.map { it.name })
            }
            is PairResult.None -> {
                return genericConfirmationCard(id, file, origName, ips, text, fields, addresses, overrides)
                    .copy(pairCandidates = stored.filter { !it.paired }.map { it.name })
            }
        }
    }

    private fun genericConfirmationCard(
        id: String,
        file: StoredFile,
        origName: String,
        ips: Map<String, String>?,
        text: String?,
        fields: com.racunko.app.parser.ConfirmationFields,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>
    ): CardItem {
        val provider = fields.provider
        val providerToken = overrides[provider]?.takeIf { it.isNotBlank() } ?: provider
        val month = MonthDetector.detect(provider, ips, text)
        val addr = AddressMatcher.detect(addresses, ips, text, provider)
        return CardItem(
            id = id, mode = CardMode.POTVRDA, origName = origName,
            uri = file.uri.toString(),
            provider = providerToken,
            address = addr.label,
            month = month,
            amount = fields.amount,
            addrAmbiguous = if (addr.ambiguous) addr.all else emptyList(),
            currentName = origName
        )
    }

    /** Manual pairing (layer 3): bind a confirmation file to a bill by its stored name. */
    suspend fun pairManually(
        conf: StoredFile,
        store: FileStore,
        billName: String
    ): Pair<Uri, String> {
        val ext = "." + conf.name.substringAfterLast('.', "pdf")
        val (newUri, newName) =
            renameTo(conf.uri, conf.name, store, FileKind.POTVRDA, "uplata_$billName", ext)
        dao.byName(billName)?.let { markPaired(it.roKey) }
        return newUri to newName
    }

    private suspend fun markPaired(roKey: String) {
        dao.setPaired(roKey, true)
        dao.byKey(roKey)?.qrImageUri?.let { joined ->
            Gallery.delete(context, joined)
            dao.clearQrUri(roKey)
        }
    }

    // ---------------------------------------------------------------- edits

    /** Re-run rename + record upsert after a manual segment edit. */
    suspend fun applyEdits(item: CardItem, store: FileStore): CardItem {
        var out = item
        val kind = if (item.mode == CardMode.RACUN) FileKind.RACUN else FileKind.POTVRDA
        if (item.isComplete) {
            val base = BillName.build(
                item.provider, item.address, item.month, item.amount,
                confirmation = item.mode == CardMode.POTVRDA
            )
            val ext = "." + item.currentName.substringAfterLast('.', "pdf")
            if (item.currentName != "$base$ext") {
                val (newUri, newName) =
                    renameTo(Uri.parse(item.uri), item.currentName, store, kind, base, ext)
                out = out.copy(uri = newUri.toString(), currentName = newName)
            }
        }
        if (item.mode == CardMode.RACUN && item.roDigits.length >= 6) {
            val existing = dao.byKey(item.roDigits)
            // keep the QR PNGs in sync with the new file name
            var qrImageUri = out.qrImageUri
            val renamed = out.currentName != item.currentName
            if (out.qrPng != null && renamed) {
                out.qrImageUri?.let { Gallery.delete(context, it) }
                val bmp = android.graphics.BitmapFactory.decodeByteArray(out.qrPng, 0, out.qrPng.size)
                if (bmp != null) {
                    qrImageUri = Gallery.save(context, bmp, "${out.nameBase}_QR", safStore(), caption = out.nameBase)
                    bmp.recycle()
                }
                out = out.copy(qrImageUri = qrImageUri)
            }
            dao.upsert(
                BillEntity(
                    roKey = item.roDigits,
                    altKey = StoredBill.altKeyOf(item.roDigits),
                    provider = out.provider,
                    address = out.address,
                    month = out.month?.month,
                    year2 = out.month?.year2,
                    amount = out.amount,
                    recipientAccount = existing?.recipientAccount ?: "",
                    finalName = out.nameBase,
                    qrImageUri = qrImageUri ?: existing?.qrImageUri,
                    paired = existing?.paired ?: false,
                    timestamp = System.currentTimeMillis()
                )
            )
        }
        return out
    }

    // -------------------------------------------------------------- helpers

    private fun uniqueIn(
        store: FileStore,
        kind: FileKind,
        base: String,
        ext: String,
        ignoreCurrent: String?
    ): String {
        val existing = store.existingNames(kind).let { names ->
            if (ignoreCurrent != null) names - ignoreCurrent else names
        }
        return BillName.unique(base, ext, existing)
    }

    private fun renameTo(
        uri: Uri,
        currentName: String,
        store: FileStore,
        kind: FileKind,
        base: String,
        ext: String
    ): Pair<Uri, String> {
        if (currentName == "$base$ext") return uri to currentName
        val target = uniqueIn(store, kind, base, ext, ignoreCurrent = currentName)
        val newUri = store.rename(uri, currentName, target, kind)
        return if (newUri != null) newUri to target else uri to currentName
    }

    /** PDFBox text; when shorter than 40 chars the PDF is image-based -> OCR (v1.1). */
    private suspend fun extractTextWithOcrFallback(uri: Uri): String? {
        val text = runCatching { PdfText.extract(context, uri) }.getOrNull()
        if (com.racunko.app.parser.OcrPolicy.needsOcr(text)) {
            val ocr = runCatching { PdfOcr.ocr(context, uri) }.getOrNull()
            if (!ocr.isNullOrBlank()) return ocr
        }
        return text
    }

    /** OCR a shared image confirmation (screenshot) via the flavor's engine. */
    suspend fun ocrImage(uri: Uri): String {
        val recognizer = Engines.instance?.textRecognizer ?: return ""
        val bmp = context.contentResolver.openInputStream(uri)?.use {
            BitmapFactory.decodeStream(it)
        } ?: return ""
        return try {
            recognizer.recognize(bmp)
        } finally {
            bmp.recycle()
        }
    }
}

private fun Bitmap.toPngBytes(): ByteArray {
    val out = ByteArrayOutputStream()
    compress(Bitmap.CompressFormat.PNG, 100, out)
    return out.toByteArray()
}
