package com.racunko.app.domain

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import com.racunko.app.data.BillDao
import com.racunko.app.data.BillEntity
import com.racunko.app.data.FileKind
import com.racunko.app.data.FileStore
import com.racunko.app.data.Gallery
import com.racunko.app.data.PayeeDao
import com.racunko.app.data.PayeeProfileEntity
import com.racunko.app.data.SafStore
import com.racunko.app.data.StoredFile
import com.racunko.app.parser.AccountChecksum
import com.racunko.app.parser.AddressEntry
import com.racunko.app.parser.AddressMatcher
import com.racunko.app.parser.AmountParser
import com.racunko.app.parser.BillName
import com.racunko.app.parser.ConfirmationParser
import com.racunko.app.parser.IpsQr
import com.racunko.app.parser.IpsQrPayload
import com.racunko.app.parser.MonthDetector
import com.racunko.app.parser.MonthYear
import com.racunko.app.parser.PairResult
import com.racunko.app.parser.PairingEngine
import com.racunko.app.parser.PayeeMemory
import com.racunko.app.parser.ProviderDetector
import com.racunko.app.parser.StoredBill
import com.racunko.app.parser.registry.NormalizedDoc
import com.racunko.app.parser.registry.SourceKind
import com.racunko.app.parser.registry.TemplateRegistry
import com.racunko.platform.Engines
import java.io.ByteArrayOutputStream

enum class CardMode { RACUN, POTVRDA }
enum class CardStatus { OK, ERROR }

data class CardItem(
    val id: String,
    val mode: CardMode,
    val origName: String,
    val uri: String,
    val provider: String = "",
    val address: String = "",
    val month: MonthYear? = null,
    val amount: Long? = null,
    val roDigits: String = "",
    /** IPS QR R field (18 digits) or account extracted from a QR-less bill. */
    val recipientAccount: String = "",
    /** Recipient name (IPS N), used when generating a QR (Change 5b). */
    val recipientName: String = "",
    /** Recipient account passed the MOD 97-10 checksum (Change 5). */
    val accountVerified: Boolean = false,
    val hasQr: Boolean = false,
    val qrPng: ByteArray? = null,
    val qrImageUri: String? = null,
    val qrNote: Boolean = false,
    /**
     * Regeneration was tried for this card and produced nothing (source file
     * gone, or too few proven fields to rebuild from). Transient — never
     * persisted; it exists so an open QR slot says why it is empty instead of
     * being a silent dead end.
     */
    val qrUnavailable: Boolean = false,
    /** The QR was generated by the app (Change 5b), not extracted from a source QR. */
    val qrGenerated: Boolean = false,
    /** Fields filled from payee memory (Change 6) — shown as "predloženo". */
    val providerSuggested: Boolean = false,
    val addressSuggested: Boolean = false,
    /** v1.5.2 Change B: canonical per-space id (InfoStan IDENT), "" when none. */
    val spaceId: String = "",
    /** v1.6: payment deadline as an epoch day; null when the bill prints none. */
    val dueDateEpochDay: Long? = null,
    /** v1.6: per-bill reminder („Podseti me da se približava plaćanje"). */
    val remindEnabled: Boolean = true,
    val remindDaysBefore: Int = 3,
    val remindHour: Int = 10,
    val remindMinute: Int = 0,
    /** v1.5.2 Change B2: the final name collides — ask for a space tag, no silent _2. */
    val needsSpaceTag: Boolean = false,
    val status: CardStatus = CardStatus.OK,
    val error: String? = null,
    /** Confirmation card: successfully paired with a bill. */
    val matched: Boolean = false,
    /** Bill card: its confirmation arrived. */
    val paired: Boolean = false,
    /** v1.3 Change 3: attached confirmation shown as a sub-row under the bill. */
    val pairedConfName: String? = null,
    val pairedConfUri: String? = null,
    /** Bill names offered as tap-to-pair chips on an unpaired confirmation card. */
    val pairCandidates: List<String> = emptyList(),
    val addrAmbiguous: List<String> = emptyList(),
    /** Current file name on disk. */
    val currentName: String
) {
    val nameBase: String get() = currentName.substringBeforeLast('.')
    val isComplete: Boolean get() = BillName.isComplete(provider, address, month, amount)
}

class Pipeline(
    private val context: Context,
    private val dao: BillDao,
    private val payeeDao: PayeeDao,
    /** v1.5.0-rc1: supplies the bound SAF store so QR PNGs land in the tree. */
    private val safStore: () -> SafStore? = { null }
) {

    private var seq = 0
    private fun nextId(): String = "card${seq++}_${System.currentTimeMillis()}"

    private val registry = TemplateRegistry.default()

    // ---------------------------------------------------------------- bills

    /** PDF bill: PDFBox text (+ OCR fallback) and PdfRenderer→QrDecoder for the IPS QR. */
    suspend fun processBill(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val origName = file.name
        val id = nextId()

        val text = extractTextWithOcrFallback(file.uri)
        var qr: QrResult? = null
        var qrFailed = false
        try {
            qr = QrExtractor.extract(context, file.uri)
        } catch (e: Exception) {
            qrFailed = true
        }
        if (text == null && qr == null) return errorCard(id, origName, file.uri)

        return buildBillCard(
            id, origName, file.uri, store, text, qr?.payload, qr?.qrPng, qrFailed,
            sourceKind = if (text.isNullOrBlank()) SourceKind.PDF_OCR else SourceKind.PDF_TEXT,
            addresses = addresses, overrides = overrides, bindings = bindings
        )
    }

    /**
     * Change 4: paper bill imported as a photo (or the still frame from 8d).
     * OCR the image and decode any photographed IPS QR directly from the bitmap
     * via the flavor engines, then share the same naming/storage logic.
     */
    suspend fun processImageBill(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val origName = file.name
        val id = nextId()
        val engines = Engines.instance
        val bmp = loadBitmap(file.uri)
        if (bmp == null || engines == null) return errorCard(id, origName, file.uri)

        val text = recognizeForOcr(bmp)
        val payload = runCatching {
            engines.qrDecoder.decodeThorough(bmp).firstOrNull { it.startsWith(IpsQr.PREFIX) }
        }.getOrNull()
        // regenerate a crisp QR PNG if an IPS code was photographed
        val qrPng = payload?.let { runCatching { engines.qrEncoder.encode(it, 660) }.getOrNull() }
        bmp.recycle()
        if (text.isNullOrBlank() && payload == null) return errorCard(id, origName, file.uri)

        return buildBillCard(
            id, origName, file.uri, store, text, payload, qrPng, qrFailed = false,
            sourceKind = SourceKind.IMAGE_OCR, addresses = addresses, overrides = overrides,
            bindings = bindings
        )
    }

    /**
     * 8d: turn a live-scanned IPS QR payload into a bill. No OCR and no
     * full-page photo (product decision) — a clean PDF artifact is generated
     * from the decoded fields + a fresh IPS QR, then run through the normal PDF
     * pipeline. Month/address come from payee memory (inside processBill) or
     * manual chips; the QR is flagged generated so the disclaimer applies.
     */
    suspend fun processScannedQr(
        payload: String,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val engines = Engines.instance ?: return errorCard(nextId(), "skenirano.pdf", Uri.EMPTY)
        val ips = IpsQr.parse(payload)
        val qr = engines.qrEncoder.encode(payload, 660)
        val lines = listOfNotNull(
            ips["N"]?.takeIf { it.isNotBlank() },
            ips["I"]?.takeIf { it.isNotBlank() }
        )
        val bytes = ScanArtifact.buildPdf(qr, lines)
        val temp = java.io.File(context.cacheDir, "scan_${System.currentTimeMillis()}.pdf")
        temp.writeBytes(bytes)
        val imported = store.importFile(
            FileKind.RACUN, Uri.fromFile(temp), "skenirano_${System.currentTimeMillis()}.pdf", "application/pdf"
        )
        runCatching { temp.delete() }
        if (imported == null) return errorCard(nextId(), "skenirano.pdf", Uri.EMPTY)

        // Build directly as QR_ONLY (no QR-derived address, Change 6) using the
        // freshly generated QR bitmap; flag it generated so the disclaimer applies.
        return buildBillCard(
            nextId(), imported.name, imported.uri, store,
            text = null, qrPayload = payload, qrPng = qr, qrFailed = false,
            sourceKind = SourceKind.QR_ONLY, addresses = addresses, overrides = overrides,
            bindings = bindings
        ).copy(qrGenerated = true)
    }

    /**
     * v1.5.2 Change A: classify a picked/shared file BEFORE import, so manual
     * add and share-into share one code path. The core's classifier decides
     * (bank-confirmation fingerprint → CONFIRMATION; bill/uplatnica fingerprint
     * or IPS QR → BILL; else UNKNOWN). Errors degrade to UNKNOWN — the app then
     * simply asks, it never blocks.
     */
    suspend fun classifyDocument(uri: Uri, isImage: Boolean): com.racunko.app.parser.registry.DocTypeGuess = try {
        val text: String?
        val qrPayload: String?
        if (isImage) {
            val bmp = loadBitmap(uri)
            val engines = Engines.instance
            if (bmp == null || engines == null) {
                text = null; qrPayload = null
            } else {
                text = recognizeForOcr(bmp)
                qrPayload = runCatching {
                    engines.qrDecoder.decodeThorough(bmp).firstOrNull { it.startsWith(IpsQr.PREFIX) }
                }.getOrNull()
                bmp.recycle()
            }
        } else {
            text = extractTextWithOcrFallback(uri)
            qrPayload = runCatching { QrExtractor.extract(context, uri)?.payload }.getOrNull()
        }
        val ips = qrPayload?.let { IpsQr.parse(it) }
        val kind = if (isImage) SourceKind.IMAGE_OCR else SourceKind.PDF_TEXT
        registry.classifyDocType(NormalizedDoc.of(text, ips, kind))
    } catch (_: Exception) {
        com.racunko.app.parser.registry.DocTypeGuess(
            com.racunko.app.parser.registry.DocType.UNKNOWN,
            com.racunko.app.parser.registry.GuessConfidence.LOW
        )
    }

    private fun errorCard(id: String, origName: String, uri: Uri) = CardItem(
        id = id, mode = CardMode.RACUN, origName = origName,
        uri = uri.toString(), status = CardStatus.ERROR, error = "PDF", currentName = origName
    )

    /**
     * Did we actually READ this document, or only receive characters from it?
     *
     * `OcrPolicy` asks whether the text is long enough; this asks whether it is
     * text at all. A PDF whose subset fonts ship no `/ToUnicode` map extracts as
     * plausible-looking Latin letters that spell nothing — „ЈАВНО КОМУНАЛНО"
     * arrives as `jabho komyhanho` — and length alone cannot tell the two apart.
     *
     * The test is deliberately blunt: every bill from every issuer prints at
     * least a couple of these words, and glyph soup prints none. It only gates
     * the GUESS (payee-memory prefill), never the reading — so a false negative
     * costs one manual tap on the address, and never a wrong file name.
     */
    private fun textIsReadable(text: String?): Boolean {
        val t = com.racunko.app.parser.Normalizer.norm(text)
        if (t.length < com.racunko.app.parser.OcrPolicy.MIN_TEXT_LENGTH) return false
        return BILL_WORDS.count { t.contains(it) } >= 2
    }

    private fun loadBitmap(uri: Uri): android.graphics.Bitmap? =
        runCatching {
            context.contentResolver.openInputStream(uri)?.use {
                android.graphics.BitmapFactory.decodeStream(it)
            }
        }.getOrNull()

    /**
     * v1.7: enlarge a small image before OCR. Tesseract wants roughly 300 DPI to
     * resolve small print; a phone SCREENSHOT of an A4 bill arrives about 1080 px
     * wide, i.e. ~130 DPI, and the rows printed smallest simply do not appear in
     * the output. [PdfOcr] already renders pages at >= 2000 px for exactly this
     * reason — the IMAGE path had no equivalent, so it read the same bill worse
     * than the PDF of it.
     *
     * Measured on device 14.08.2026, Cyrillic InfoStan bill, gms release:
     * at 1080x2340 the „Датум доспећа" row was missing from 4359 characters of
     * otherwise correct text (address matched, provider and amount right) and the
     * deadline came out empty; at 2160x4680 the same bill yields 4582 characters,
     * the row reads, and `DueDateParser` returns 31.08.2026 — the printed date.
     * Cost was 2.7 s -> 3.4 s, NOT the 4x the pixel count suggests, because the
     * work scales with the text found rather than with the area scanned.
     *
     * Only ever scales UP, and never past [OCR_MAX_PIXELS] so a large photo is
     * left alone (it is already sharp enough, and enlarging it would risk OOM).
     */
    private fun scaledForOcr(bmp: android.graphics.Bitmap): android.graphics.Bitmap {
        if (bmp.width >= OCR_MIN_WIDTH) return bmp
        // WHOLE-NUMBER factor, deliberately. `createScaledBitmap` is bilinear, and
        // at a fractional factor every glyph edge lands between source pixels and
        // comes out smeared — measured on device 14.08.2026: 1080 -> 2000 (1.85x)
        // READ THE ADDRESS WORSE THAN THE UNSCALED ORIGINAL, losing a line the
        // native image had. At 2x each source pixel maps onto a whole block, edges
        // survive, and the same bill reads both its address and its deadline.
        // So: round the factor UP rather than hitting the target width exactly.
        val factor = ((OCR_MIN_WIDTH + bmp.width - 1) / bmp.width).coerceAtLeast(1)
        val w = bmp.width * factor
        val h = bmp.height * factor
        if (w.toLong() * h.toLong() > OCR_MAX_PIXELS) return bmp
        return runCatching {
            android.graphics.Bitmap.createScaledBitmap(bmp, w, h, true)
        }.getOrDefault(bmp)
    }

    /** OCR on an enlarged copy, releasing the copy but never the caller's bitmap. */
    private suspend fun recognizeForOcr(bmp: android.graphics.Bitmap): String? {
        val engines = Engines.instance ?: return null
        val big = scaledForOcr(bmp)
        return try {
            runCatching { engines.textRecognizer.recognize(big) }.getOrNull()
        } finally {
            if (big !== bmp) big.recycle()
        }
    }

    /** Shared bill logic for both the PDF and image inputs. */
    private suspend fun buildBillCard(
        id: String,
        origName: String,
        sourceUri: Uri,
        store: FileStore,
        text: String?,
        qrPayload: String?,
        qrPng: android.graphics.Bitmap?,
        qrFailed: Boolean,
        sourceKind: SourceKind,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        bindings: List<com.racunko.app.parser.SpaceBinding> = emptyList()
    ): CardItem {
        val ext = "." + origName.substringAfterLast('.', "pdf")
        val ips = qrPayload?.let { IpsQr.parse(it) }
        val rawProvider = ProviderDetector.detect(ips, text)
        val amount = AmountParser.parse(ips, text)
        val month = MonthDetector.detect(rawProvider, ips, text)
        // Change 6: on a scanned/QR-only bill the address is NEVER taken from the
        // QR (P is the payer's address, not the user's label) — pass no QR, so
        // the label comes from payee memory below or stays a manual "adresa?".
        val addrIps = if (sourceKind == SourceKind.QR_ONLY) null else ips
        val addr = AddressMatcher.detect(addresses, addrIps, text, rawProvider)

        // Change 5: recipient account (QR R, else extracted from a QR-less bill),
        // gated by the MOD 97-10 checksum — an unverified account never enables
        // QR generation and is not a pairing key.
        val recipientAccount = if (ips != null) {
            IpsQr.recipientAccountDigits(ips)
        } else {
            runCatching {
                registry.extract(NormalizedDoc.of(text, ips, sourceKind)).recipientAccount
            }.getOrNull().orEmpty()
        }
        val accountVerified = AccountChecksum.isValid(recipientAccount)
        val recipientName = ips?.get("N")?.trim().orEmpty()

        // Change 6 / v1.4.4 Change 4: prefill missing provider/address from a
        // remembered payee — but NEVER on the scan path (QR_ONLY): a scanned
        // bill's address is always blank for manual entry, no guess at all.
        //
        // v1.7: the same refusal when the DOCUMENT COULD NOT BE READ. Found on
        // device 14.08.2026: an InfoStan bill whose fonts carry no ToUnicode map
        // extracts as 4461 characters of glyph soup — long enough to pass the
        // OCR gate, legible to nobody. The address matcher then finds nothing,
        // and payee memory fills the blank from the RECIPIENT ACCOUNT — which
        // for InfoStan is one institutional account shared by every customer and
        // every flat. It cannot identify an address, so what it supplies is
        // whichever address was seen last. That is a guess, and it renamed a
        // bill onto the wrong address.
        //
        // OCR is not a way out of THIS one either. Since v1.7 both flavors read
        // Cyrillic (D1: Tesseract with `srp`), so a screenshot of such a bill now
        // does parse — but this gate is about a document that came back
        // unreadable for any reason at all, glyph soup included, and for that one
        // the app does what it says it does: when a value cannot be proven, it asks.
        val prefill = if (sourceKind == SourceKind.QR_ONLY || !textIsReadable(text)) {
            com.racunko.app.parser.PrefillResult(rawProvider, addr.label, false, false)
        } else {
            val profile = if (accountVerified) payeeDao.byAccount(recipientAccount)?.toProfile() else null
            PayeeMemory.prefill(recipientAccount, rawProvider, addr.label) { profile }
        }
        // v1.5.2 Change B: the per-space id (InfoStan IDENT) picks up a bound
        // sub-label once set — SG26 becomes SG26-G1 automatically, every month.
        val spaceId = com.racunko.app.parser.SpaceId.detect(rawProvider, ips, text) ?: ""
        // v1.6: the deadline is read from its printed label, or stays empty for
        // an optional manual entry — never guessed from the issue date.
        val dueDate = com.racunko.app.parser.DueDateParser.parse(text)
        val subLabel = com.racunko.app.parser.SpaceNaming.subFor(spaceId, prefill.addressLabel, bindings)
        val addressLabel = com.racunko.app.parser.SpaceNaming.addressToken(prefill.addressLabel, subLabel)
        val providerToken = overrides[prefill.provider]?.takeIf { it.isNotBlank() } ?: prefill.provider

        var currentName = origName
        var currentUri = sourceUri
        var needsSpaceTag = false
        if (BillName.isComplete(providerToken, addressLabel, month, amount)) {
            val base = BillName.build(providerToken, addressLabel, month, amount)
            // reprocessing an already-renamed file keeps its name
            if (origName != "$base$ext" && !BillName.PROCESSED.matches(origName)) {
                val existing = store.existingNames(FileKind.RACUN) - origName
                if (com.racunko.app.parser.SpaceNaming.collides(base, ext, existing, origName)) {
                    // Change B2: identical final name (another space?) — no silent
                    // _2 suffix; the card asks for a space tag instead.
                    needsSpaceTag = true
                } else {
                    store.rename(currentUri, origName, "$base$ext", FileKind.RACUN)?.let {
                        currentUri = it
                        currentName = "$base$ext"
                    }
                }
            }
        }

        val nameBase = currentName.substringBeforeLast('.')
        val ro = IpsQr.roDigits(ips)
        val qrBytes = qrPng?.toPngBytes()

        // The QR is no longer written anywhere by default. It is cached for
        // display — cacheDir, which the system owns — and leaves the app only
        // when the user taps „Podeli QR" or „Sačuvaj u galeriju". Seeding the
        // cache here is free: the bitmap is already decoded, so a freshly
        // processed bill never pays for a PdfRenderer pass to show its code.
        if (qrBytes != null) {
            QrCache.write(context, QrCache.keyFor(ro, nameBase), QrBytes(qrBytes, generated = false))
        }

        var alreadyPaired = false
        // A gallery copy saved in an earlier round stays on the record, so
        // pairing still knows what to delete.
        var qrImageUri: String? = null
        if (ro.length >= 6) {
            val existing = dao.byKey(ro)
            alreadyPaired = existing?.paired ?: false
            qrImageUri = existing?.qrImageUri
            dao.upsert(
                BillEntity(
                    roKey = ro,
                    altKey = StoredBill.altKeyOf(ro),
                    provider = providerToken,
                    address = addressLabel,
                    month = month?.month,
                    year2 = month?.year2,
                    amount = amount,
                    recipientAccount = recipientAccount,
                    finalName = nameBase,
                    qrImageUri = qrImageUri,
                    paired = alreadyPaired,
                    timestamp = System.currentTimeMillis()
                )
            )
        }

        // Remember this payee for next month (checksum-valid accounts only).
        rememberPayee(recipientAccount, accountVerified, prefill.provider, addressLabel, recipientName, ro)

        return CardItem(
            id = id,
            mode = CardMode.RACUN,
            origName = origName,
            uri = currentUri.toString(),
            provider = providerToken,
            address = addressLabel,
            month = month,
            amount = amount,
            roDigits = ro,
            recipientAccount = recipientAccount,
            recipientName = recipientName,
            accountVerified = accountVerified,
            hasQr = qrPayload != null,
            qrPng = qrBytes,
            qrImageUri = qrImageUri,
            qrNote = qrFailed,
            paired = alreadyPaired,
            providerSuggested = prefill.providerSuggested,
            addressSuggested = prefill.addressSuggested,
            spaceId = spaceId,
            dueDateEpochDay = dueDate?.toEpochDay(),
            needsSpaceTag = needsSpaceTag,
            addrAmbiguous = if (addr.ambiguous) addr.all else emptyList(),
            currentName = currentName
        )
    }

    /**
     * Change 5b: generate an NBS IPS QR for a bill that has none. Gated on a
     * checksum-valid recipient account + present amount (the same gate the UI
     * enforces). The PNG is cached for display only — nothing is written to the
     * gallery until the user asks for it.
     */
    suspend fun generateQr(item: CardItem): CardItem {
        val png = buildQrFromFields(item) ?: return item
        QrCache.write(context, QrCache.keyFor(item.roDigits, item.nameBase), QrBytes(png, generated = true))
        return item.copy(
            qrPng = png,
            hasQr = true,
            qrGenerated = true,
            qrUnavailable = false
        )
    }

    /**
     * Books a gallery copy the user just asked for against the BILL record.
     *
     * This is what makes the automatic delete-on-pairing possible: `markPaired`
     * reads `qrImageUri` off the bill row, and since the storage round nothing
     * else writes it any more — the copy exists only because someone tapped
     * „U galeriju". Without this call the bill would be paid and the QR would
     * stay in the gallery for good.
     */
    suspend fun recordSavedQr(item: CardItem, joinedUris: String) {
        if (item.roDigits.length < 6) return
        dao.byKey(item.roDigits)?.let { dao.upsert(it.copy(qrImageUri = joinedUris)) }
    }

    /** The gallery copy currently booked for this bill, if any. */
    suspend fun savedQrUris(item: CardItem): String? =
        if (item.roDigits.length < 6) null else dao.byKey(item.roDigits)?.qrImageUri

    /**
     * The QR bytes for a card that has none in memory — a restored card
     * (v1.4.3), or any card after a cold start, since the bitmap is not stored.
     *
     * Order matters. The issuer's own code is read back from the DOCUMENT first,
     * because a code rebuilt from the stored fields is not the same payload: the
     * payee name, payment code and model are not reconstructed literally. Only
     * when the document cannot give it up do we rebuild — and that result is
     * marked generated, so the card shows the verify-before-paying notice even
     * though the bill originally carried a real QR.
     *
     * Both paths land in [QrCache]; the expensive one (PdfRenderer + decode) is
     * therefore paid once per bill, not once per cold start.
     */
    suspend fun qrFor(item: CardItem): QrBytes? {
        val key = QrCache.keyFor(item.roDigits, item.nameBase)
        val started = System.currentTimeMillis()
        QrCache.read(context, key)?.let { logQr("cache", started); return it }
        val fresh = deriveQr(item)
        if (fresh == null) {
            logQr("none", started)
            return null
        }
        QrCache.write(context, key, fresh)
        logQr(if (fresh.generated) "rebuilt" else "document", started)
        return fresh
    }

    /**
     * How the code was obtained and what it cost — the one number the device
     * pass has to see, since „open the QR on every unpaid card" is only sound if
     * a cold start is cheap. Deliberately carries NO key and NO file name: the
     * reference number identifies a person's account and has no business in a
     * log buffer other apps can read.
     */
    private fun logQr(source: String, startedAt: Long) {
        android.util.Log.d("RacunkoQr", "qr source=$source ms=${System.currentTimeMillis() - startedAt}")
    }

    private suspend fun deriveQr(item: CardItem): QrBytes? {
        // A code this app generated is not in the document — skip straight to
        // rebuilding rather than paying for a render that cannot succeed.
        if (!item.qrGenerated) {
            decodeFromSource(item)?.let { return QrBytes(it, generated = false) }
        }
        return buildQrFromFields(item)?.let { QrBytes(it, generated = true) }
    }

    /** Re-reads the IPS QR out of the source file — PDF page render, or the image itself. */
    private suspend fun decodeFromSource(item: CardItem): ByteArray? {
        val uri = runCatching { Uri.parse(item.uri) }.getOrNull() ?: return null
        runCatching { QrExtractor.extract(context, uri)?.qrPng }
            .getOrNull()?.let { return it.toPngBytes() }
        // PdfRenderer throws on a photographed bill; decode the bitmap directly.
        if (!item.currentName.endsWith(".pdf", ignoreCase = true)) {
            val engines = Engines.instance ?: return null
            val bmp = loadBitmap(uri) ?: return null
            val png = runCatching {
                engines.qrDecoder.decodeThorough(bmp).firstOrNull { it.startsWith(IpsQr.PREFIX) }
                    ?.let { engines.qrEncoder.encode(it, 660).toPngBytes() }
            }.getOrNull()
            bmp.recycle()
            return png
        }
        return null
    }

    /** Assembles an IPS QR from the fields the database keeps; null when unproven. */
    private fun buildQrFromFields(item: CardItem): ByteArray? {
        if (!IpsQrPayload.canGenerate(item.recipientAccount, item.amount)) return null
        val engines = Engines.instance ?: return null
        val payload = IpsQrPayload.build(
            recipientAccount = item.recipientAccount,
            recipientName = item.recipientName.ifBlank { item.provider.uppercase() },
            amount = item.amount!!,
            paymentReference = item.roDigits.ifBlank { null }
        )
        return runCatching { engines.qrEncoder.encode(payload, 660).toPngBytes() }.getOrNull()
    }

    private suspend fun rememberPayee(
        account: String,
        accountVerified: Boolean,
        provider: String,
        address: String,
        displayName: String,
        referenceShape: String
    ) {
        if (!accountVerified || provider.isBlank() || address.isBlank()) return
        payeeDao.upsert(
            PayeeProfileEntity(
                account = account,
                provider = provider,
                addressLabel = address,
                displayName = displayName.ifBlank { provider },
                lastReferenceShape = referenceShape,
                updatedAt = System.currentTimeMillis()
            )
        )
    }

    // -------------------------------------------------------- confirmations

    suspend fun processConfirmation(
        file: StoredFile,
        store: FileStore,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>,
        ocrText: String? = null
    ): CardItem {
        val origName = file.name
        val id = nextId()
        val isImage = ocrText != null

        val text: String? = if (isImage) ocrText else extractTextWithOcrFallback(file.uri)
        val qr: QrResult? = if (isImage) null else {
            runCatching { QrExtractor.extract(context, file.uri) }.getOrNull()
        }
        if (text == null && qr == null) {
            return CardItem(
                id = id, mode = CardMode.POTVRDA, origName = origName,
                uri = file.uri.toString(), status = CardStatus.ERROR,
                error = "PDF", currentName = origName
            )
        }

        val ips = qr?.let { IpsQr.parse(it.payload) }
        val fields = ConfirmationParser.parse(text ?: "", ips)
        val stored = dao.all().map { it.toStored() }
        val ext = "." + (origName.substringAfterLast('.', "pdf"))

        when (val result = PairingEngine.pair(fields, stored)) {
            is PairResult.Matched -> {
                val bill = result.bill
                val (newUri, newName) =
                    renameTo(file.uri, origName, store, FileKind.POTVRDA, "uplata_${bill.name}", ext)
                markPaired(bill.roKey)
                return CardItem(
                    id = id, mode = CardMode.POTVRDA, origName = origName,
                    uri = newUri.toString(),
                    provider = bill.provider, address = bill.address,
                    month = bill.month, amount = bill.amount,
                    matched = true, currentName = newName
                )
            }
            is PairResult.Candidates -> {
                return genericConfirmationCard(id, file, origName, ips, text, fields, addresses, overrides)
                    .copy(pairCandidates = result.bills.map { it.name })
            }
            is PairResult.None -> {
                return genericConfirmationCard(id, file, origName, ips, text, fields, addresses, overrides)
                    .copy(pairCandidates = stored.filter { !it.paired }.map { it.name })
            }
        }
    }

    private fun genericConfirmationCard(
        id: String,
        file: StoredFile,
        origName: String,
        ips: Map<String, String>?,
        text: String?,
        fields: com.racunko.app.parser.ConfirmationFields,
        addresses: List<AddressEntry>,
        overrides: Map<String, String>
    ): CardItem {
        val provider = fields.provider
        val providerToken = overrides[provider]?.takeIf { it.isNotBlank() } ?: provider
        val month = MonthDetector.detect(provider, ips, text)
        val addr = AddressMatcher.detect(addresses, ips, text, provider)
        return CardItem(
            id = id, mode = CardMode.POTVRDA, origName = origName,
            uri = file.uri.toString(),
            provider = providerToken,
            address = addr.label,
            month = month,
            amount = fields.amount,
            addrAmbiguous = if (addr.ambiguous) addr.all else emptyList(),
            currentName = origName
        )
    }

    /** Manual pairing (layer 3): bind a confirmation file to a bill by its stored name. */
    suspend fun pairManually(
        conf: StoredFile,
        store: FileStore,
        billName: String
    ): Pair<Uri, String> {
        val ext = "." + conf.name.substringAfterLast('.', "pdf")
        val (newUri, newName) =
            renameTo(conf.uri, conf.name, store, FileKind.POTVRDA, "uplata_$billName", ext)
        dao.byName(billName)?.let { markPaired(it.roKey) }
        return newUri to newName
    }

    /**
     * The bill is paid, so a QR the user saved to the gallery has done its job
     * and is removed — it can always be shown again, since the code is derived,
     * not stored.
     *
     * THE LIMIT, which must not be relaxed: only the uris Računko itself wrote
     * and recorded in `qrImageUri` are deleted. The gallery is never searched
     * for „something that looks like a QR". The app removes only what it made.
     */
    private suspend fun markPaired(roKey: String) {
        dao.setPaired(roKey, true)
        dao.byKey(roKey)?.qrImageUri?.let { joined ->
            Gallery.delete(context, joined)
            dao.clearQrUri(roKey)
        }
    }

    // ---------------------------------------------------------------- edits

    /** Re-run rename + record upsert after a manual segment edit. */
    suspend fun applyEdits(item: CardItem, store: FileStore): CardItem {
        var out = item
        val kind = if (item.mode == CardMode.RACUN) FileKind.RACUN else FileKind.POTVRDA
        if (item.isComplete) {
            val base = BillName.build(
                item.provider, item.address, item.month, item.amount,
                confirmation = item.mode == CardMode.POTVRDA
            )
            val ext = "." + item.currentName.substringAfterLast('.', "pdf")
            if (item.currentName != "$base$ext") {
                val (newUri, newName) =
                    renameTo(Uri.parse(item.uri), item.currentName, store, kind, base, ext)
                // A bill with no reference number is cached under its file name,
                // so the old entry is now unreachable — drop it.
                if (item.roDigits.isBlank()) {
                    QrCache.remove(context, QrCache.keyFor("", item.nameBase))
                }
                out = out.copy(uri = newUri.toString(), currentName = newName)
            }
        }
        if (item.mode == CardMode.RACUN && item.roDigits.length >= 6) {
            val existing = dao.byKey(item.roDigits)
            var qrImageUri = out.qrImageUri
            val renamed = out.currentName != item.currentName
            // A gallery copy carries the file name in its caption band, so a
            // rename has to redo it — but only if the user asked for one in the
            // first place. Nothing is published here on its own account.
            val png = out.qrPng
            if (renamed && qrImageUri != null && png != null) {
                Gallery.delete(context, qrImageUri)
                val bmp = android.graphics.BitmapFactory.decodeByteArray(png, 0, png.size)
                qrImageUri = if (bmp != null) {
                    Gallery.save(context, bmp, "${out.nameBase}_QR", safStore(), caption = out.nameBase)
                        .also { bmp.recycle() }
                } else null
                out = out.copy(qrImageUri = qrImageUri)
            }
            dao.upsert(
                BillEntity(
                    roKey = item.roDigits,
                    altKey = StoredBill.altKeyOf(item.roDigits),
                    provider = out.provider,
                    address = out.address,
                    month = out.month?.month,
                    year2 = out.month?.year2,
                    amount = out.amount,
                    recipientAccount = existing?.recipientAccount ?: "",
                    finalName = out.nameBase,
                    qrImageUri = qrImageUri ?: existing?.qrImageUri,
                    paired = existing?.paired ?: false,
                    timestamp = System.currentTimeMillis()
                )
            )
        }
        return out
    }

    // -------------------------------------------------------------- helpers

    private fun uniqueIn(
        store: FileStore,
        kind: FileKind,
        base: String,
        ext: String,
        ignoreCurrent: String?
    ): String {
        val existing = store.existingNames(kind).let { names ->
            if (ignoreCurrent != null) names - ignoreCurrent else names
        }
        return BillName.unique(base, ext, existing)
    }

    private fun renameTo(
        uri: Uri,
        currentName: String,
        store: FileStore,
        kind: FileKind,
        base: String,
        ext: String
    ): Pair<Uri, String> {
        if (currentName == "$base$ext") return uri to currentName
        val target = uniqueIn(store, kind, base, ext, ignoreCurrent = currentName)
        val newUri = store.rename(uri, currentName, target, kind)
        return if (newUri != null) newUri to target else uri to currentName
    }

    /** PDFBox text; when shorter than 40 chars the PDF is image-based -> OCR (v1.1). */
    private suspend fun extractTextWithOcrFallback(uri: Uri): String? {
        val text = runCatching { PdfText.extract(context, uri) }.getOrNull()
        if (com.racunko.app.parser.OcrPolicy.needsOcr(text)) {
            val ocr = runCatching { PdfOcr.ocr(context, uri) }.getOrNull()
            if (!ocr.isNullOrBlank()) return ocr
        }
        return text
    }

    /** OCR a shared image confirmation (screenshot) via the flavor's engine. */
    suspend fun ocrImage(uri: Uri): String {
        val bmp = context.contentResolver.openInputStream(uri)?.use {
            BitmapFactory.decodeStream(it)
        } ?: return ""
        return try {
            recognizeForOcr(bmp).orEmpty()
        } finally {
            bmp.recycle()
        }
    }
}

/**
 * Words a Serbian utility bill prints in some form, normalized the way
 * `Normalizer` leaves them (diacritics folded, Cyrillic transliterated). Used
 * only to tell real text from glyph soup — see `Pipeline.textIsReadable`.
 */
private val BILL_WORDS = listOf(
    "racun", "uplat", "iznos", "ukupno", "dinar", "primalac", "platilac",
    "poziv na broj", "svrha", "zaduzenj", "duguje", "obracun", "period", "potrosnj"
)

/** Width an image is enlarged to before OCR — the same target [PdfOcr] renders at. */
private const val OCR_MIN_WIDTH = 2000

/** Ceiling for the enlarged copy, so a big photo is never blown up into an OOM. */
private const val OCR_MAX_PIXELS = 40_000_000L

private fun Bitmap.toPngBytes(): ByteArray {
    val out = ByteArrayOutputStream()
    compress(Bitmap.CompressFormat.PNG, 100, out)
    return out.toByteArray()
}
